[plugin]
name = "dokku-dyno-hostname"
description = "Dynamically sets the docker hostname option for dokku"
version = "0.0.1"
website_url = "https://github.com/neamar/dokku-dyno-hostname"
[plugin.config]
